import fetchImage from "@/utils/image-utils";
import { IMAGES } from "../image-constants";

export const PRODUCTS = {
  // 🆕 NEW ARRIVALS
  newArrivals: [
    {
      id: 1,
      name: "T-shirt with Tape details",
      price: 120,
      rating: 4.5,
      image: fetchImage(IMAGES.BLACK_TSHIRT),
    },
    {
      id: 2,
      name: "Skinny Fit Jeans",
      price: 240,
      oldPrice: 260,
      rating: 3.5,
      discount: "-20%",
      image: fetchImage(IMAGES.SKINNY_JEANS), // ✅ Uses Frame 33.png
    },
    {
      id: 3,
      name: "Checkered Shirt",
      price: 180,
      rating: 4.5,
      image: fetchImage(IMAGES.CHECKERED_SHIRT),
    },
    {
      id: 4,
      name: "Sleeve Striped T-Shirt",
      price: 130,
      oldPrice: 160,
      rating: 4.5,
      discount: "-30%",
      image: fetchImage(IMAGES.STRIPED_TSHIRT),
    },
  ],

  // 🛒 TOP SELLING
  topSelling: [
    {
      id: 5,
      name: "Vertical Striped Shirt",
      price: 212,
      oldPrice: 232,
      rating: 5.0,
      discount: "-20%",
      image: fetchImage(IMAGES.GREEN_SHIRT),
    },
    {
      id: 6,
      name: "Courage Graphic T-Shirt",
      price: 145,
      rating: 4.0,
      image: fetchImage(IMAGES.ORANGE_TSHIRT),
    },
    {
      id: 7,
      name: "Loose Fit Bermuda Shorts",
      price: 80,
      rating: 3.0,
      image: fetchImage(IMAGES.BLUE_SHORTS),
    },
    {
      id: 8,
      name: "Fadded Skinny Jeans",
      price: 210,
      rating: 4.5,
      image: fetchImage(IMAGES.FADED_SKINNY_JEANS), // ✅ Changed to use new constant name
    },
  ],

  // 💡 YOU MIGHT ALSO LIKE
  youMightAlsoLike: [
    {
      id: 9,
      name: "Polo with Contrast Trims",
      price: 212,
      oldPrice: 242,
      rating: 4.0,
      discount: "-20%",
      image: fetchImage(IMAGES.SHIRT),
    },
    {
      id: 10,
      name: "Gradient Graphic T-shirt",
      price: 145,
      rating: 3.6,
      image: fetchImage(IMAGES.MIX_SHIRT),
    },
    {
      id: 11,
      name: "Polo with Tipping Details",
      price: 180,
      rating: 4.5,
      image: fetchImage(IMAGES.BROWN_SHIRT),
    },
    {
      id: 12,
      name: "Black Striped T-shirt",
      price: 120,
      oldPrice: 160,
      discount: "-30%",
      rating: 5.0,
      image: fetchImage(IMAGES.BLACK_SHIRT),
    },
  ],

  // 👕 CATEGORY PRODUCTS
  categories: [
    {
      id: 1,
      name: "Gradient Graphic T-shirt",
      image: fetchImage(IMAGES.T_SHIRT),
      price: 145,
      // oldPrice: 190,
      rating: 3.5,
      // discount: "25%",
      category: "T-shirts",
      color: "pink",
      size: "L",
    },
    {
      id: 2,
      name: "Polo with Tipping Details",
      image: fetchImage(IMAGES.POLO_SHIRT),
      price: 180,
      // oldPrice: 210,
      rating: 4.5,
      // discount: "15%",
      category: "T-shirts",
      color: "brown",
      size: "M",
    },
    {
      id: 3,
      name: "Black Striped T-shirt",
      image: fetchImage(IMAGES.BALCK_TSHIRT),
      price: 120,
      oldPrice: 150,
      rating: 5.0,
      discount: "-30%",
      category: "T-shirts",
      color: "black",
      size: "S",
    },
    {
      id: 4,
      name: "Skinny Fit Jeans",
      image: fetchImage(IMAGES.JEANS),
      price: 240,
      oldPrice: 260,
      rating: 3.5,
      discount: "-20%",
      category: "Jeans",
      color: "blue",
      size: "L",
    },
    {
      id: 5,
      name: "Checkered Shirt",
      image: fetchImage(IMAGES.BLUE_SHIRT),
      price: 180,
      // oldPrice: 220,
      rating: 4.5,
      // discount: "18%",
      category: "Shirts",
      color: "red",
      size: "M",
    },
    {
      id: 6,
      name: "Sleeve Striped Shirt",
      image: fetchImage(IMAGES.OB_TSHIRT),
      price: 130,
      oldPrice: 160,
      rating: 4.7,
      discount: "-30%",
      category: "Shirts",
      color: "green",
      size: "L",
    },
    {
      id: 7,
      name: "Vertical Stripped Shirt",
      image: fetchImage(IMAGES.SLEEVE_TSHIRT),
      price: 212,
      oldPrice: 232,
      rating: 4.0,
      discount: "-20%",
      category: "Shirts",
      color: "blue",
      size: "S",
    },
    {
      id: 8,
      name: "Courage Graphic T-Shirt",
      image: fetchImage(IMAGES.COURAGE_TSHIRT),
      price: 145,
      // oldPrice: 232,
      rating: 4.0,
      // discount: "9%",
      category: "T-Shirts",
      color: "orange",
      size: "L",
    },
    {
      id: 9,
      name: "Loose Fit Bermuda Shorts",
      image: fetchImage(IMAGES.BERMUDA),
      price: 80,
      // oldPrice: 100,
      // rating: 3.0,
      discount: "-20%",
      category: "Shorts",
      color: "blue",
      size: "S",
    },
  ],
};
