// ✅ Corrected product-constants.js

import fetchImage from "@/utils/image-utils";
import { IMAGES } from "@/constants/image-constants"; // ✅ correct import path

export const PRODUCTS = {
  //  NEW ARRIVALS
  newArrivals: [
    {
      id: 1,
      name: "t-shirt-with-tape-details",
      price: 120,
      rating: 4.5,
      image: fetchImage(IMAGES.BLACK_TSHIRT),
    },
    {
      id: 2,
      name: "skinny-fit-jeans",
      price: 240,
      oldPrice: 260,
      rating: 3.5,
      discount: "-20%",
      image: fetchImage(IMAGES.SKINNY_JEANS),
    },
    {
      id: 3,
      name: "checkered-shirt",
      price: 180,
      rating: 4.5,
      image: fetchImage(IMAGES.CHECKERED_SHIRT),
    },
    {
      id: 4,
      name: "sleeve-striped-t-shirt",
      price: 130,
      oldPrice: 160,
      rating: 4.5,
      discount: "-30%",
      image: fetchImage(IMAGES.STRIPED_TSHIRT),
    },
  ],

  //  TOP SELLING
  topSelling: [
    {
      id: 5,
      name: "vertical-striped-shirt",
      price: 212,
      oldPrice: 232,
      rating: 5.0,
      discount: "-20%",
      image: fetchImage(IMAGES.GREEN_SHIRT),
    },
    {
      id: 6,
      name: "courage-graphic-t-shirt",
      price: 145,
      rating: 4.0,
      image: fetchImage(IMAGES.ORANGE_TSHIRT),
    },
    {
      id: 7,
      name: "loose-fit-bermuda-shorts",
      price: 80,
      rating: 3.0,
      image: fetchImage(IMAGES.BLUE_SHORTS),
    },
    {
      id: 8,
      name: "fadded-skinny-jeans",
      price: 210,
      rating: 4.5,
      image: fetchImage(IMAGES.FADED_SKINNY_JEANS),
    },
  ],

  //  YOU MIGHT ALSO LIKE
  youMightAlsoLike: [
    {
      id: 9,
      name: "Polo with Contrast Trims",
      price: 212,
      oldPrice: 242,
      rating: 4.0,
      discount: "-20%",
      image: fetchImage(IMAGES.SHIRT),
    },
    {
      id: 10,
      name: "Gradient Graphic T-shirt",
      price: 145,
      rating: 3.6,
      image: fetchImage(IMAGES.MIX_SHIRT),
    },
    {
      id: 11,
      name: "Polo with Tipping Details",
      price: 180,
      rating: 4.5,
      image: fetchImage(IMAGES.BROWN_SHIRT),
    },
    {
      id: 12,
      name: "Black Striped T-shirt",
      price: 120,
      oldPrice: 160,
      discount: "-30%",
      rating: 5.0,
      image: fetchImage(IMAGES.BLACK_SHIRT),
    },
  ],

  //  CATEGORY PRODUCTS
  categories: [
    {
      id: 1,
      name: "gradient-graphic-t-shirt",
      image: fetchImage(IMAGES.T_SHIRT),
      price: 145,
      rating: 3.5,
      category: "T-shirts",
      color: "Pink",
      size: "Large",
      dressStyle: "Casual",
    },
    {
      id: 2,
      name: "polo-with-tipping-details",
      image: fetchImage(IMAGES.POLO_SHIRT),
      price: 180,
      rating: 4.5,
      category: "T-shirts",
      color: "Brown",
      size: "Medium",
      dressStyle: "Casual",
    },
    {
      id: 3,
      name: "black-striped-t-shirt",
      image: fetchImage(IMAGES.BLACK_TSHIRT),
      price: 120,
      oldPrice: 150,
      rating: 5.0,
      discount: "-30%",
      category: "T-shirts",
      color: "Black",
      size: "Small",
      dressStyle: "Casual",
    },
    {
      id: 4,
      name: "skinny-fit-jeans",
      image: fetchImage(IMAGES.JEANS),
      price: 240,
      oldPrice: 260,
      rating: 3.5,
      discount: "-20%",
      category: "Jeans",
      color: "Blue",
      size: "Large",
      dressStyle: "Casual",
    },
    {
      id: 5,
      name: "checkered-shirt",
      image: fetchImage(IMAGES.BLUE_SHIRT),
      price: 180,
      rating: 4.5,
      category: "Shirts",
      color: "Red",
      size: "Medium",
      dressStyle: "Formal",
    },
    {
      id: 6,
      name: "sleeve-striped-shirt",
      image: fetchImage(IMAGES.OB_TSHIRT),
      price: 130,
      oldPrice: 160,
      rating: 4.7,
      discount: "-30%",
      category: "Shirts",
      color: "Green",
      size: "Large",
      dressStyle: "Casual",
    },
    {
      id: 7,
      name: "vertical-stripped-shirt",
      image: fetchImage(IMAGES.SLEEVE_TSHIRT),
      price: 212,
      oldPrice: 232,
      rating: 4.0,
      discount: "-20%",
      category: "Shirts",
      color: "Blue",
      size: "Small",
      dressStyle: "Formal",
    },
    {
      id: 8,
      name: "courage-graphic-t-shirt",
      image: fetchImage(IMAGES.COURAGE_TSHIRT),
      price: 145,
      rating: 4.0,
      category: "T-shirts",
      color: "Orange",
      size: "Large",
      dressStyle: "Party",
    },
    {
      id: 9,
      name: "loose-fit-bermuda-shorts",
      image: fetchImage(IMAGES.BERMUDA),
      price: 80,
      discount: "-20%",
      category: "Shorts",
      color: "Blue",
      size: "Small",
      dressStyle: "Gym",
    },
  ],
};
